uploads = []
generated = []

[[outputs]]
id = "jNaYsQmCQNnaT0rgMpxYy"
uri = "file://.local/exports/project.tar.gz"
type = "unspecified"
title = "Project source (excludes node_modules/build artifacts)"
